# Generated by Django 4.2.1 on 2023-05-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'programer',
            },
        ),
    ]
