# Generated by Django 4.2.1 on 2023-05-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programer',
            name='score',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
